[package]
name = "day17"
version = "0.1.0"
authors = ["matei-oltean <matei.oltean@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reader = { path = "../reader" }
intcode = { path = "../intcode" }